# Generated by Django 4.0.6 on 2022-08-01 13:24

from django.db import migrations, models
import gag.helpers


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(upload_to=gag.helpers.UploadTo('profile')),
        ),
    ]
